baseURL = 'https://www.bwdfwd.com/'
languageCode = 'en-us'
title = 'BwdFwd'
theme = "shibui"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[params]
  author = "Your Name"
  email = "your.email@example.com"
  math = true

[menu]
  [[menu.main]]
    name = "Research"
    url = "/Research/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/Posts/"
    weight = 2
  [[menu.main]]
    name = "ML Summaries"
    url = "/Summaries/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
